import { z } from "zod"

/**
 * Vocabulary shared by every kernel entity.
 */

/** Every row gets one. Generated by the database, not by application code. */
export const id = z.uuid()
export type Id = z.infer<typeof id>

/**
 * Which part of the product a row belongs to. Stamped on jobs and sessions so the
 * kernel can carry work without learning what any of it means.
 */
export const domainId = z.string().min(1)
export type DomainId = z.infer<typeof domainId>

/** ISO 3166-1 alpha-2, lowercased — the form the proxy layer takes. */
export const countryCode = z
  .string()
  .length(2)
  .regex(/^[a-z]{2}$/, "country must be lowercase ISO 3166-1 alpha-2")
export type CountryCode = z.infer<typeof countryCode>

/** A key in object storage. The engine never dereferences one; it hands it to the caller. */
export const storageRef = z.string().min(1)
export type StorageRef = z.infer<typeof storageRef>

/** Added to every entity. Executors do not repeat these per schema. */
export const timestamps = z.object({
  createdAt: z.date(),
  updatedAt: z.date(),
})
